### ISSUE TITLE
Need a button to refresh what accounts the authenticated google account has access to.

### ISSUE THREAD

**Issue by corsacca** [ChasmSolutions/disciple-tools-analytics#1]
Currently The only way to re sign-in or get a more up to date of list of Google Analytics Accounts is to deactivate and then reactive the plugin.

**Comment by ChrisChasm** [comment]
Good observations:
- If the processing and connections to Google went correctly, then we are in good shape to start building forward. My plan is to use this base framework to extract key metrics and store for local reporting, to allow multiple accounts to be assigned, etc. 
- The caching of information is to reduce the traffic to the API. We can talk about it, but this plugin is not meant to replace the full toolset in Google Analytics, but rather to connect to a larger reporting system, and the give core statistics within the Disciple Tools system. 

Thanks for taking the time to test it bro!
